version: '3'

services:
  db:
    image: mysql
    restart: always
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: '${DB_HOST}'

  api:
    image: cam/gdrive_api
    depends_on:
      - db
    build: ./server
    ports: 
      - '${API_PORT}:${API_PORT}'
    restart: always
    volumes:
      - ./.env:/app/.env
    networks:
      backend:
        ipv4_address: '${API_HOST}'
        
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: '${BACKEND_SUBNET}'

  # web:
  #   image: cam/gdrive_web
  #   build: ./web
  #   ports: '${WEB_PORT}:${WEB_PORT}'
  #   restart: always