version: '3'

services:
  # api:
  #   image: cam/gdrive_api
  #   build: ./api
  #   ports: '${API_PORT}:${API_PORT}'
  #   restart: always
      
  db:
    image: mysql
    restart: always
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
    # env_file:
    #   - ./config.env

  # web:
  #   image: cam/gdrive_web
  #   build: ./web
  #   ports: '${WEB_PORT}:${WEB_PORT}'
  #   restart: always