version: '3.3'

services:
  db:
    image: mysql
    container_name: gdc_db
    restart: always
    env_file: .env
    command: --default-authentication-plugin=caching_sha2_password
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: '${DB_HOST}'
    healthcheck:
      test: ['CMD','mysqladmin', '-u', '${DB_USER}', '-p${DB_PASS}', 'ping', '-h', '${DB_HOST}']
      interval: 1s
      timeout: 2s
      retries: 20
  
  api:
    image: cam/gdc_app
    container_name: gdc_app
    restart: always
    env_file: ./.env
    build: ./app
    ports: 
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./app/data/files:/app/data/files:rw  # files
      # - ./app/src:/app/src         # live dev
      - ./.env:/app/.env:ro        # env
    networks:
      backend:
        ipv4_address: '${API_HOST}'

volumes:
  mysql_data:


  # web:
  #   image: cam/gdc_web
  #   container_name: gdc_web
  #   restart: always
  #   env_file: ./.env
  #   build: ./web
  #   ports:
  #     - '${WEB_PORT}:3000'
  #   networks:
  #     backend:
  #       ipv4_address: '${WEB_HOST}'
  #   volumes:
  #     - type: bind
  #       source: ./web/app/src
  #       target: /app/src
  #     - type: bind
  #       source: ./web/app/public
  #       target: /app/public
  #     # - ./app/node_modules
  #     # - ./app/.next
  #     # - ./web/app/src:/app/src:ro
  #     - ./.env:/app/.env:ro

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: '${BACKEND_SUBNET}'
