version: '3.3'

services:
  db:
    image: mysql
    container_name: gdc_db
    restart: always
    env_file: .env
    command: --default-authentication-plugin=caching_sha2_password
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: '${DB_HOST}'
    healthcheck:
      test: ['CMD','mysqladmin', '-u', '${DB_USER}', '-p${DB_PASS}', 'ping', '-h', '${DB_HOST}']
      interval: 1s
      timeout: 2s
      retries: 20
  
  api:
    image: cam/gdc_app
    container_name: gdc_app
    restart: always
    env_file: ./.env
    build: ./app
    ports: 
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./data:/app/data/files:rw
      - ./.env:/app/.env:ro
    networks:
      backend:
        ipv4_address: '${API_HOST}'

volumes:
  mysql_data:

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: '${BACKEND_SUBNET}'
