version: '3.3'

services:
  db:
    image: mysql
    container_name: gdc_db
    restart: always
    env_file: ./.env
    command: --default-authentication-plugin=caching_sha2_password
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      backend:
        ipv4_address: '${DB_HOST}'
    healthcheck:
      test: ['CMD','mysqladmin', '-u', '${DB_USER}', '-p${DB_PASS}', 'ping', '-h', '${DB_HOST}']
      interval: 1s
      timeout: 2s
      retries: 100

  api:
    image: cam/gdrive_api
    container_name: gdc_api
    restart: always
    build: ./server
    ports: 
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./server/files:/app/files:rw  # saved files
      - ./server/src:/app/src:ro      # live dev - works.. kinda?? - weird lol
      - ./.env:/app/.env:ro           # env
    networks:
      backend:
        ipv4_address: '${API_HOST}'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD','curl', '${API_HOST}:${API_PORT}/api/test']
      interval: 1s
      timeout: 2s
      retries: 100
  
  web:
    image: cam/gdrive_web
    container_name: gdc_web
    restart: always
    env_file: ./.env
    build: ./web
    ports:
      - '${WEB_PORT}:3000'
    networks:
      backend:
        ipv4_address: '${WEB_HOST}'
    volumes:
      - ./.env:/app/.env:ro

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: '${BACKEND_SUBNET}'
