version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE: "${MYSQL_ROOT_DATABASE}"
    ports: 
      - '${DB_PORT}:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: '${DB_HOST}'
    healthcheck:
      test: ['CMD','mysqladmin', '-u', '${DB_USER}', '-p${DB_PASS}', 'ping', '-h', '${DB_HOST}']
      interval: 1s
      timeout: 2s
      retries: 100

  api:
    image: cam/gdrive_api
    build: ./server
    ports: 
      - '${API_PORT}:${API_PORT}'
    restart: always
    volumes:
      - ./.env:/app/.env
    networks:
      backend:
        ipv4_address: '${API_HOST}'
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: '${BACKEND_SUBNET}'

  # web:
  #   image: cam/gdrive_web
  #   build: ./web
  #   ports: '${WEB_PORT}:${WEB_PORT}'
  #   restart: always