CREATE DATABASE IF NOT EXISTS GDRIVEDB;
USE GDRIVEDB;

CREATE TABLE USER (
  ID CHAR(36) DEFAULT(uuid()) PRIMARY KEY,
  USERNAME VARCHAR(32) UNIQUE NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  CREATED DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE FILE_OBJECT (
  ID CHAR(36) DEFAULT(uuid()) PRIMARY KEY,

  EXTENSION VARCHAR(64) NOT NULL,

  INTERNAL_FILE_PATH TEXT NOT NULL,
  SIZE_BYTES FLOAT NOT NULL,

  UPLOAD_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_DOWNLOAD_TIME DATETIME,
  LAST_DOWNLOAD_USER_ID CHAR(36),

  FOREIGN KEY (LAST_DOWNLOAD_USER_ID) REFERENCES USER(ID)
);

CREATE TABLE DIRECTORY (
	ID CHAR(36) DEFAULT(uuid()) NOT NULL UNIQUE,

	# default is ROOT folder which is all 0s
	PARENT_ID CHAR(36) DEFAULT('000000000000000000000000000000000000') NOT NULL, 
	OWNER_ID CHAR(36) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	COLOR CHAR(7) NOT NULL DEFAULT '#737373',

	FOREIGN KEY (PARENT_ID) REFERENCES DIRECTORY(ID),
	FOREIGN KEY (OWNER_ID) REFERENCES USER(ID),

	PRIMARY KEY (PARENT_ID, OWNER_ID, NAME)
);

CREATE TABLE AUTH (
	USER_ID CHAR(36),
	TOKEN CHAR(36) NOT NULL UNIQUE,
	EXPIRES DATETIME NOT NULL,

	PRIMARY KEY (USER_ID, TOKEN),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID) 
);

CREATE TABLE FILE_INSTANCE (
  USER_ID CHAR(36),
  FILE_ID CHAR(36),
  PARENT_FOLDER_ID CHAR(36),
  IS_OWNER BIT(1) DEFAULT 0,

  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION TEXT,

  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (FILE_ID) REFERENCES FILE_OBJECT(ID),
	FOREIGN KEY (PARENT_FOLDER_ID) REFERENCES DIRECTORY(ID),

  PRIMARY KEY (USER_ID, FILE_ID)
);

CREATE TABLE COMMENT (
  FILE_ID CHAR(36) NOT NULL,
  USER_ID CHAR(36) NOT NULL,
  COMMENT TEXT NOT NULL,

  FOREIGN KEY (FILE_ID) REFERENCES FILE_INSTANCE(FILE_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),

  PRIMARY KEY (FILE_ID, USER_ID)
);
