cd /docker-entrypoint-initdb.d

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $MYSQL_ROOT_DATABASE;"

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE USER '$DB_USER'@'$API_HOST' IDENTIFIED WITH caching_sha2_password BY '$DB_PASS';";
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE USER '$DB_USER'@'$BACKEND_GATEWAY' IDENTIFIED WITH caching_sha2_password BY '$DB_PASS';";

mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE $MYSQL_ROOT_DATABASE.* TO '$DB_USER'@'$API_HOST';"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE $MYSQL_ROOT_DATABASE.* TO '$DB_USER'@'$BACKEND_GATEWAY';"
