USE GDRIVEDB;

CREATE TABLE USER (
  EMAIL VARCHAR(64) PRIMARY KEY,
  APIK CHAR(36) DEFAULT(uuid()) UNIQUE,
  PASSWORD VARCHAR(32) NOT NULL
);

CREATE TABLE FILE (
  ID CHAR(36) DEFAULT(uuid()) PRIMARY KEY,
  FILENAME VARCHAR(255) NOT NULL,
  EXTENSION VARCHAR(32) NOT NULL,
  DESCRIPTION TEXT,

  INTERNAL_FILE_PATH VARCHAR(255) NOT NULL,
  SIZE_BYTES INT NOT NULL,

  UPLOAD_TIME DATE DEFAULT(NOW()) NOT NULL,
  ORIGINAL_OWNER_EMAIL VARCHAR(64) NOT NULL,
  LAST_DOWNLOAD_TIME DATE,
  LAST_DOWNLOAD_USER_EMAIL VARCHAR(64),

  FOREIGN KEY (ORIGINAL_OWNER_EMAIL) REFERENCES USER(EMAIL)
);

CREATE TABLE OWNERSHIP (
  USER_EMAIL VARCHAR(64),
  FILE_ID CHAR(36),

  PRIMARY KEY (USER_EMAIL, FILE_ID),
  FOREIGN KEY (USER_EMAIL) REFERENCES USER(EMAIL),
  FOREIGN KEY (FILE_ID) REFERENCES FILE(ID)
);
