cd /docker-entrypoint-initdb.d

EXEC_SQL=$(mysql -u root -p$MYSQL_ROOT_PASSWORD -e)

$EXEC_SQL "CREATE DATABASE $MYSQL_ROOT_DATABASE;"

$EXEC_SQL "CREATE USER '$DB_USER'@'$API_HOST' IDENTIFIED WITH caching_sha2_password BY '$DB_PASS';";
$EXEC_SQL "CREATE USER '$DB_USER'@'$BACKEND_GATEWAY' IDENTIFIED WITH caching_sha2_password BY '$DB_PASS';";

$EXEC_SQL "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE $MYSQL_ROOT_DATABASE.* TO '$DB_USER'@'$API_HOST';"
$EXEC_SQL "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE $MYSQL_ROOT_DATABASE.* TO '$DB_USER'@'$BACKEND_GATEWAY';"
