USE GDRIVEDB;

CREATE TABLE USER (
  ID CHAR(36) DEFAULT(uuid()) PRIMARY KEY,
  
  EMAIL VARCHAR(64) UNIQUE NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  CREATED DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_LOGGED_IN DATETIME
);

CREATE TABLE FILE (
  ID CHAR(36) DEFAULT(uuid()) PRIMARY KEY,

  /* FILENAME VARCHAR(255) NOT NULL, */
  NAME VARCHAR(255) NOT NULL,
  EXTENSION VARCHAR(10) NOT NULL,
  FILE_TYPE VARCHAR(32) NOT NULL,
  OWNER_ID CHAR(36) NOT NULL,
  DESCRIPTION TEXT,

  INTERNAL_FILE_PATH TEXT NOT NULL,
  SIZE_BYTES FLOAT NOT NULL,

  UPLOAD_TIME DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_DOWNLOAD_TIME DATETIME,
  LAST_DOWNLOAD_USER_ID CHAR(36),

  FOREIGN KEY (OWNER_ID) REFERENCES USER(ID),
  FOREIGN KEY (LAST_DOWNLOAD_USER_ID) REFERENCES USER(ID)
);

CREATE TABLE COMMENT (
  FILE_ID CHAR(36) NOT NULL,
  USER_ID CHAR(36) NOT NULL,
  COMMENT TEXT NOT NULL,

  FOREIGN KEY (FILE_ID) REFERENCES FILE(ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),

  PRIMARY KEY (FILE_ID, USER_ID)
);

CREATE TABLE OWNERSHIP (
  USER_ID CHAR(36),
  FILE_ID CHAR(36),
  PARENT_FOLDER_ID CHAR(36),
  HAS_VIEWED BIT(1) DEFAULT 0,

  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (FILE_ID) REFERENCES FILE(ID),

  PRIMARY KEY (USER_ID, FILE_ID)
);
